# Generated by Django 4.2.27 on 2025-12-12 12:10

from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[utils.validator.mobile_validator], verbose_name='شماره تلفن'),
        ),
    ]
