# Generated by Django 4.2.27 on 2025-12-12 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='article',
            new_name='blog',
        ),
    ]
