# Generated by Django 4.2.27 on 2025-12-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_rename_article_comment_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='blog',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='لینک تلگرام'),
        ),
        migrations.AddField(
            model_name='blog',
            name='x',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ایکس'),
        ),
        migrations.AddField(
            model_name='blog',
            name='youtube',
            field=models.URLField(blank=True, null=True, verbose_name='لینک یوتیوب'),
        ),
    ]
