# Generated by Django 4.2.27 on 2025-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_instagram_blog_telegram_blog_x_blog_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='video_link',
            field=models.URLField(blank=True, null=True, verbose_name='لینک ویدیو اموزشی'),
        ),
    ]
