# Generated by Django 4.2.27 on 2025-12-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_coursecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(blank=True, choices=[('preliminary', 'مقدماتی'), ('Medium', 'متوسط'), ('advanced', 'پیشرفته')], max_length=20, null=True, verbose_name='سطح دوره'),
        ),
    ]
